export const initialState = {
    fullDesc: '',
    transmission: '',
    stockNo: '',
    year: 2015,
    make: '',
    model: '',
    color: '',
    cylinder: "",
    displacement: "",
    mileage: "",
    bodyType: '',
    secondDesc: '',
    trim: '',
    options: [],
    photos: [],
    mediaUrls: [],
    previewURLS: [],
};